import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useServerFn } from '@tanstack/react-start';
import { BookOpen, Check, ChevronLeft, RefreshCw, Swords, Users } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { UserAvatar } from './UserAvatar';
import { useSession } from './session';
import { fetchGuildWars, updateGuildWar, enterGuildWarMatch } from '@/lib/guild-wars.functions';
import { WAR_RULES, sameFighter, type WarSide, type GuildWar } from '@/lib/guild-wars';
import type { PublicGuild } from '@/lib/game';
import challengerArt from '@/assets/bg-8.jpg.asset.json';
import defenderArt from '@/assets/bg-6.jpg.asset.json';

function WarTeam({ side, tone }: { side: WarSide; tone: 'challenger' | 'defender' }) {
  return <div className={`war-team war-${tone}`}><UserAvatar name={side.name} src={side.iconUrl} className="size-16 rounded-lg border-2 sm:size-20" /><p className="war-label mt-3">{tone}</p><h3 className="mt-1 text-lg font-bold sm:text-xl">{side.name}</h3><p className="text-muted-foreground mt-2 text-xs sm:text-sm">{side.fighters.length} fighters · Guild level {side.level}</p></div>;
}
export function GuildWars({ guilds, initialWarId, onBack }: { guilds: PublicGuild[]; initialWarId?: string; onBack: () => void }) {
  const { data: user } = useSession(); const client = useQueryClient();
  const getWars = useServerFn(fetchGuildWars); const act = useServerFn(updateGuildWar); const enter = useServerFn(enterGuildWarMatch);
  const [rules, setRules] = useState(false); const [selectedId, setSelectedId] = useState(initialWarId); const [filter, setFilter] = useState('All'); const [now, setNow] = useState<number | null>(null);
  useEffect(() => { setNow(Date.now()); const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const query = useQuery({ queryKey: ['aidoru', 'guild-wars'], queryFn: () => getWars(), enabled: Boolean(user), refetchInterval: 15_000, retry: false });
  const mutation = useMutation({ mutationFn: (data: { warId: string; action: 'accept' | 'decline' | 'register' | 'withdraw' }) => act({ data }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['aidoru', 'guild-wars'] }); toast.success('War status updated'); }, onError: (e: Error) => toast.error(e.message) });
  const enterMutation = useMutation({ mutationFn: (data: { warId: string; matchId: string }) => enter({ data }), onSuccess: (result) => { setRoomId(result.roomId); }, onError: (e: Error) => toast.error(e.message) });
  const [roomId, setRoomId] = useState<string | null>(null);
  const wars = query.data ?? []; const war = wars.find(w => w.id === selectedId) ?? wars[0];
  const mine = guilds.find(g => g.isMember); const mySide = war && mine ? [war.challenger, war.defender].find(s => s.id === mine.id) : undefined;
  const registered = mySide?.fighters.some(f => user && sameFighter(f.id, user.id));
  const remaining = war && now ? Math.max(0, war.deadline - now) : null;
  const time = remaining === null ? '—' : remaining >= 86_400_000 ? `${Math.floor(remaining / 86_400_000)}d ${Math.floor(remaining / 3_600_000) % 24}h` : `${Math.floor(remaining / 3_600_000)}h ${Math.floor(remaining / 60_000) % 60}m`;
  return <div className="guild-interface space-y-6">
    <div className="flex flex-wrap items-center gap-3"><span className="war-icon"><Swords /></span><h1 className="mr-auto text-2xl font-bold">Guild Wars</h1><Button variant="outline" size="icon" onClick={onBack} aria-label="Back to guilds"><ChevronLeft /></Button><Button variant="outline" size="icon" onClick={() => setRules(true)} aria-label="Guild war rules" title="Guild war rules"><BookOpen /></Button><Button variant="outline" className="war-refresh" onClick={() => void query.refetch()} disabled={query.isFetching}><RefreshCw className={query.isFetching ? 'animate-spin' : ''} />Refresh status</Button></div>
    {query.isError ? <div className="war-empty"><p>{query.error.message}</p><Button variant="outline" onClick={() => void query.refetch()}>Try again</Button></div> : query.isPending ? <div className="war-empty">Loading wars…</div> : !war ? <div className="war-empty"><Swords className="mx-auto mb-4 size-12 text-primary" /><h2 className="text-xl font-bold">No wars yet</h2><Button className="mt-5" onClick={onBack}>Find a guild to challenge</Button></div> : <>
    {wars.length > 1 && <select aria-label="Select guild war" className="guild-input w-full" value={war.id} onChange={e => { setSelectedId(e.target.value); setRoomId(null); }}>{wars.map(w => <option key={w.id} value={w.id}>{w.challenger.name} vs {w.defender.name} · {w.phase}</option>)}</select>}
    <section className="war-overview"><div className="war-backdrops" aria-hidden="true"><img src={war.challenger.bannerUrl || challengerArt.url} alt="" /><img src={war.defender.bannerUrl || defenderArt.url} alt="" /></div><div className="relative p-5 text-center sm:p-8"><span className={`war-phase ${war.phase === 'battle' ? 'is-battle' : ''}`}><span className="size-2 rounded-full bg-current" />{war.phase === 'battle' ? 'Battle phase' : war.phase}</span><div className="war-score"><strong className="war-challenger">{war.challenger.score}</strong><Swords className="text-muted-foreground size-8" /><strong className="war-defender">{war.defender.score}</strong></div><p className="text-muted-foreground text-sm">{['challenge', 'preparation', 'battle'].includes(war.phase) ? <>Ends in <strong className="text-foreground">{time}</strong></> : resultLabel(war)}</p><div className="mt-7 grid grid-cols-2 gap-5"><WarTeam side={war.challenger} tone="challenger" /><WarTeam side={war.defender} tone="defender" /></div>
    {war.phase === 'challenge' && mine?.id === war.defender.id && mine.isOwner && <div className="mt-6 flex justify-center gap-3"><Button disabled={mutation.isPending} onClick={() => mutation.mutate({ warId: war.id, action: 'accept' })}>Accept challenge</Button><Button variant="outline" disabled={mutation.isPending} onClick={() => mutation.mutate({ warId: war.id, action: 'decline' })}>Decline</Button></div>}
    {war.phase === 'preparation' && mySide && <Button className="mt-6" disabled={mutation.isPending} onClick={() => mutation.mutate({ warId: war.id, action: registered ? 'withdraw' : 'register' })}><Users />{registered ? 'Withdraw fighter' : 'Register as fighter'}</Button>}
    </div><div className="war-timeline">{['Challenge', 'Preparation', 'Battle'].map((phase, i) => { const step = ['challenge', 'preparation', 'battle', 'finished'].indexOf(war.phase); return <div key={phase} className={step === i ? 'is-current' : ''}><span className="war-step">{step > i ? <Check className="size-4" /> : i + 1}</span><div><strong>{phase}</strong><p>{['24h to respond', '15m roster lock', '48h to fight'][i]}</p></div></div>; })}</div></section>
    {roomId && <Button asChild><Link to="/battle/$roomId" params={{ roomId }}><Swords />Open battle room</Link></Button>}
    <section className="war-matchups"><div className="border-b border-border pb-5"><h2 className="text-xl font-bold sm:text-2xl">Active matchups</h2><div className="mt-4 flex gap-2" role="tablist" aria-label="Matchup status">{['All', 'Pending', 'Finished'].map(tab => <Button role="tab" aria-selected={tab === filter} key={tab} variant="ghost" className={tab === filter ? 'war-tab-active' : 'text-muted-foreground'} onClick={() => setFilter(tab)}>{tab}</Button>)}</div></div><p className="war-label mt-5">Round 1</p><div className="mt-4 space-y-3">{war.matches.filter(m => filter === 'All' || (filter === 'Finished' ? m.completedAt : !m.completedAt)).map(match => <article className="war-match" key={match.id}><div className="war-challenger"><UserAvatar name={match.challenger.name} src={match.challenger.avatarUrl} className="mx-auto size-12 border-2" /><p className="text-foreground mt-2 text-xs font-bold sm:text-sm">{match.challenger.name}</p></div><div><p className="text-xl font-bold">{match.completedAt ? `${sameFighter(match.winnerId || '', match.challenger.id) ? 1 : 0} — ${sameFighter(match.winnerId || '', match.defender.id) ? 1 : 0}` : '— vs —'}</p><p className={`mt-1 text-[10px] font-bold uppercase ${match.completedAt ? 'text-war-success' : 'text-muted-foreground'}`}>{match.completedAt ? 'Completed' : 'Pending'}</p>{!match.completedAt && war.phase === 'battle' && user && [match.challenger, match.defender].some(f => sameFighter(f.id, user.id)) && <Button size="sm" className="mt-2" disabled={enterMutation.isPending} onClick={() => enterMutation.mutate({ warId: war.id, matchId: match.id })}>Fight</Button>}</div><div className="war-defender"><UserAvatar name={match.defender.name} src={match.defender.avatarUrl} className="mx-auto size-12 border-2" /><p className="text-foreground mt-2 text-xs font-bold sm:text-sm">{match.defender.name}</p></div></article>)}{!war.matches.length && <p className="py-8 text-center text-sm text-muted-foreground">{war.phase === 'preparation' ? 'Fighter registration is open.' : 'No matchups available.'}</p>}{war.matches.length > 0 && !war.matches.some(m => filter === 'All' || (filter === 'Finished' ? m.completedAt : !m.completedAt)) && <p className="py-8 text-center text-muted-foreground">No {filter.toLowerCase()} matchups.</p>}</div></section>
    {war.phase === 'preparation' && <section><h2 className="mb-4 text-xl font-bold">Registered fighters</h2><div className="grid gap-4 sm:grid-cols-2">{[war.challenger, war.defender].map(s => <div key={s.id}><h3 className="mb-3 text-sm font-semibold">{s.name}</h3>{s.fighters.map(f => <div key={f.id} className="flex items-center gap-3 py-2"><UserAvatar name={f.name} src={f.avatarUrl} className="size-8" /><span className="text-sm">{f.name}</span></div>)}{!s.fighters.length && <p className="text-sm text-muted-foreground">No fighters registered</p>}</div>)}</div></section>}
    </>}
    <Dialog open={rules} onOpenChange={setRules}><DialogContent className="war-rules max-h-[90dvh] w-[calc(100%-2rem)] overflow-y-auto"><DialogTitle className="flex items-center gap-4 text-xl"><span className="war-icon"><Swords /></span>Guild war rules</DialogTitle><DialogDescription className="sr-only">Challenge, preparation, battle, and recovery rules.</DialogDescription><div className="space-y-3">{WAR_RULES.map((rule, index) => <article className="war-rule" key={rule.title}><p className="text-primary text-xs font-bold">0{index + 1}</p><h3 className="mt-3 text-lg font-bold">{rule.title}</h3><p className="text-muted-foreground mt-2 text-sm leading-relaxed">{rule.text}</p></article>)}</div></DialogContent></Dialog>
  </div>;
}
function resultLabel(war: GuildWar) { return war.phase === 'finished' ? war.winnerGuildId ? `${war.winnerGuildId === war.challenger.id ? war.challenger.name : war.defender.name} wins` : 'Draw' : war.phase === 'declined' ? 'Challenge declined' : 'Challenge expired'; }