// Generated from Kelin-MD2/lib/pokemon/martItems.mjs.
// Keep this snapshot aligned with the bot catalogue when the bot shop changes.
export const BOT_MART_ITEMS = [
  {
    id: "pokeball",
    slug: "poke-ball",
    name: "Poke Ball",
    description: "See .mart page 1 for details.",
    emoji: "⚪",
    category: "ball",
    page: 1,
    price: 200,
    index: 1,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/poke-ball.png",
  },
  {
    id: "greatball",
    slug: "great-ball",
    name: "Great Ball",
    description: "See .mart page 1 for details.",
    emoji: "🔵",
    category: "ball",
    page: 1,
    price: 600,
    index: 2,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/great-ball.png",
  },
  {
    id: "ultraball",
    slug: "ultra-ball",
    name: "Ultra Ball",
    description: "See .mart page 1 for details.",
    emoji: "⚫",
    category: "ball",
    page: 1,
    price: 1200,
    index: 3,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ultra-ball.png",
  },
  {
    id: "masterball",
    slug: "master-ball",
    name: "Master Ball",
    description: "See .mart page 1 for details.",
    emoji: "🟣",
    category: "ball",
    page: 1,
    price: 3500,
    index: 4,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/master-ball.png",
  },
  {
    id: "premierball",
    slug: "premier-ball",
    name: "Premier Ball",
    description: "See .mart page 1 for details.",
    emoji: "⚪",
    category: "ball",
    page: 1,
    price: 200,
    index: 5,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/premier-ball.png",
  },
  {
    id: "healball",
    slug: "heal-ball",
    name: "Heal Ball",
    description: "See .mart page 1 for details.",
    emoji: "🩷",
    category: "ball",
    page: 1,
    price: 300,
    index: 6,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heal-ball.png",
  },
  {
    id: "duskball",
    slug: "dusk-ball",
    name: "Dusk Ball",
    description: "See .mart page 1 for details.",
    emoji: "🌑",
    category: "ball",
    page: 1,
    price: 1000,
    index: 7,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dusk-ball.png",
  },
  {
    id: "netball",
    slug: "net-ball",
    name: "Net Ball",
    description: "See .mart page 1 for details.",
    emoji: "🟩",
    category: "ball",
    page: 1,
    price: 1000,
    index: 8,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/net-ball.png",
  },
  {
    id: "luxuryball",
    slug: "luxury-ball",
    name: "Luxury Ball",
    description: "See .mart page 1 for details.",
    emoji: "🟠",
    category: "ball",
    page: 1,
    price: 1000,
    index: 9,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/luxury-ball.png",
  },
  {
    id: "quickball",
    slug: "quick-ball",
    name: "Quick Ball",
    description: "See .mart page 1 for details.",
    emoji: "🟡",
    category: "ball",
    page: 1,
    price: 1000,
    index: 10,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/quick-ball.png",
  },
  {
    id: "beastball",
    slug: "beast-ball",
    name: "Beast Ball",
    description: "See .mart page 1 for details.",
    emoji: "🔶",
    category: "ball",
    page: 1,
    price: 12000,
    index: 11,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/beast-ball.png",
  },
  {
    id: "potion",
    slug: "potion",
    name: "Potion",
    description: "See .mart page 2 for details.",
    emoji: "🩹",
    category: "heal",
    page: 2,
    price: 300,
    index: 12,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/potion.png",
  },
  {
    id: "superpotion",
    slug: "super-potion",
    name: "Super Potion",
    description: "See .mart page 2 for details.",
    emoji: "💊",
    category: "heal",
    page: 2,
    price: 700,
    index: 13,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/super-potion.png",
  },
  {
    id: "hyperpotion",
    slug: "hyper-potion",
    name: "Hyper Potion",
    description: "See .mart page 2 for details.",
    emoji: "💉",
    category: "heal",
    page: 2,
    price: 1500,
    index: 14,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hyper-potion.png",
  },
  {
    id: "fullrestore",
    slug: "full-restore",
    name: "Full Restore",
    description: "See .mart page 2 for details.",
    emoji: "✨",
    category: "heal",
    page: 2,
    price: 3000,
    index: 15,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/full-restore.png",
  },
  {
    id: "revive",
    slug: "revive",
    name: "Revive",
    description: "See .mart page 2 for details.",
    emoji: "💫",
    category: "heal",
    page: 2,
    price: 1500,
    index: 16,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/revive.png",
  },
  {
    id: "maxrevive",
    slug: "max-revive",
    name: "Max Revive",
    description: "See .mart page 2 for details.",
    emoji: "⭐",
    category: "heal",
    page: 2,
    price: 4000,
    index: 17,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-revive.png",
  },
  {
    id: "freshwater",
    slug: "fresh-water",
    name: "Fresh Water",
    description: "See .mart page 2 for details.",
    emoji: "💧",
    category: "heal",
    page: 2,
    price: 200,
    index: 18,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fresh-water.png",
  },
  {
    id: "sodapop",
    slug: "soda-pop",
    name: "Soda Pop",
    description: "See .mart page 2 for details.",
    emoji: "🥤",
    category: "heal",
    page: 2,
    price: 300,
    index: 19,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/soda-pop.png",
  },
  {
    id: "lemonade",
    slug: "lemonade",
    name: "Lemonade",
    description: "See .mart page 2 for details.",
    emoji: "🍋",
    category: "heal",
    page: 2,
    price: 350,
    index: 20,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lemonade.png",
  },
  {
    id: "moomoomilk",
    slug: "moomoo-milk",
    name: "Moomoo Milk",
    description: "See .mart page 2 for details.",
    emoji: "🥛",
    category: "heal",
    page: 2,
    price: 500,
    index: 21,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moomoo-milk.png",
  },
  {
    id: "energypowder",
    slug: "energy-powder",
    name: "Energy Powder",
    description: "See .mart page 2 for details.",
    emoji: "🌿",
    category: "heal",
    page: 2,
    price: 400,
    index: 22,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/energy-powder.png",
  },
  {
    id: "energyroot",
    slug: "energy-root",
    name: "Energy Root",
    description: "See .mart page 2 for details.",
    emoji: "🌱",
    category: "heal",
    page: 2,
    price: 800,
    index: 23,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/energy-root.png",
  },
  {
    id: "xattack",
    slug: "x-attack",
    name: "X Attack",
    description: "See .mart page 3 for details.",
    emoji: "⚔️",
    category: "battle",
    page: 3,
    price: 500,
    index: 24,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-attack.png",
  },
  {
    id: "xdefense",
    slug: "x-defense",
    name: "X Defense",
    description: "See .mart page 3 for details.",
    emoji: "🛡️",
    category: "battle",
    page: 3,
    price: 550,
    index: 25,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-defense.png",
  },
  {
    id: "xspeed",
    slug: "x-speed",
    name: "X Speed",
    description: "See .mart page 3 for details.",
    emoji: "💨",
    category: "battle",
    page: 3,
    price: 350,
    index: 26,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-speed.png",
  },
  {
    id: "xspatk",
    slug: "x-sp-atk",
    name: "X Sp Atk",
    description: "See .mart page 3 for details.",
    emoji: "🔮",
    category: "battle",
    page: 3,
    price: 500,
    index: 27,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-sp-atk.png",
  },
  {
    id: "xspdef",
    slug: "x-sp-def",
    name: "X Sp Def",
    description: "See .mart page 3 for details.",
    emoji: "🔵",
    category: "battle",
    page: 3,
    price: 550,
    index: 28,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-sp-def.png",
  },
  {
    id: "xaccuracy",
    slug: "x-accuracy",
    name: "X Accuracy",
    description: "See .mart page 3 for details.",
    emoji: "🎯",
    category: "battle",
    page: 3,
    price: 400,
    index: 29,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/x-accuracy.png",
  },
  {
    id: "guardspec",
    slug: "guard-spec",
    name: "Guard Spec",
    description: "See .mart page 3 for details.",
    emoji: "🔒",
    category: "battle",
    page: 3,
    price: 700,
    index: 30,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/guard-spec.png",
  },
  {
    id: "direhit",
    slug: "dire-hit",
    name: "Dire Hit",
    description: "See .mart page 3 for details.",
    emoji: "💥",
    category: "battle",
    page: 3,
    price: 650,
    index: 31,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dire-hit.png",
  },
  {
    id: "firestone",
    slug: "fire-stone",
    name: "Fire Stone",
    description: "See .mart page 4 for details.",
    emoji: "🔥",
    category: "stone",
    page: 4,
    price: 3000,
    index: 32,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fire-stone.png",
  },
  {
    id: "waterstone",
    slug: "water-stone",
    name: "Water Stone",
    description: "See .mart page 4 for details.",
    emoji: "💧",
    category: "stone",
    page: 4,
    price: 3000,
    index: 33,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/water-stone.png",
  },
  {
    id: "thunderstone",
    slug: "thunder-stone",
    name: "Thunder Stone",
    description: "See .mart page 4 for details.",
    emoji: "⚡",
    category: "stone",
    page: 4,
    price: 3000,
    index: 34,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/thunder-stone.png",
  },
  {
    id: "leafstone",
    slug: "leaf-stone",
    name: "Leaf Stone",
    description: "See .mart page 4 for details.",
    emoji: "🍃",
    category: "stone",
    page: 4,
    price: 3000,
    index: 35,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leaf-stone.png",
  },
  {
    id: "moonstone",
    slug: "moon-stone",
    name: "Moon Stone",
    description: "See .mart page 4 for details.",
    emoji: "🌙",
    category: "stone",
    page: 4,
    price: 3000,
    index: 36,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moon-stone.png",
  },
  {
    id: "sunstone",
    slug: "sun-stone",
    name: "Sun Stone",
    description: "See .mart page 4 for details.",
    emoji: "☀️",
    category: "stone",
    page: 4,
    price: 3000,
    index: 37,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sun-stone.png",
  },
  {
    id: "icestone",
    slug: "ice-stone",
    name: "Ice Stone",
    description: "See .mart page 4 for details.",
    emoji: "🧊",
    category: "stone",
    page: 4,
    price: 3000,
    index: 38,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ice-stone.png",
  },
  {
    id: "shinystone",
    slug: "shiny-stone",
    name: "Shiny Stone",
    description: "See .mart page 4 for details.",
    emoji: "✨",
    category: "stone",
    page: 4,
    price: 4000,
    index: 39,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shiny-stone.png",
  },
  {
    id: "dawnstone",
    slug: "dawn-stone",
    name: "Dawn Stone",
    description: "See .mart page 4 for details.",
    emoji: "🌅",
    category: "stone",
    page: 4,
    price: 4000,
    index: 40,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dawn-stone.png",
  },
  {
    id: "duskstone",
    slug: "dusk-stone",
    name: "Dusk Stone",
    description: "See .mart page 4 for details.",
    emoji: "🌆",
    category: "stone",
    page: 4,
    price: 4000,
    index: 41,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dusk-stone.png",
  },
  {
    id: "antidote",
    slug: "antidote",
    name: "Antidote",
    description: "See .mart page 5 for details.",
    emoji: "🟢",
    category: "cure",
    page: 5,
    price: 100,
    index: 42,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/antidote.png",
  },
  {
    id: "paralyzeheal",
    slug: "paralyze-heal",
    name: "Paralyze Heal",
    description: "See .mart page 5 for details.",
    emoji: "⚡",
    category: "cure",
    page: 5,
    price: 200,
    index: 43,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/paralyze-heal.png",
  },
  {
    id: "awakening",
    slug: "awakening",
    name: "Awakening",
    description: "See .mart page 5 for details.",
    emoji: "☀️",
    category: "cure",
    page: 5,
    price: 250,
    index: 44,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/awakening.png",
  },
  {
    id: "burnheal",
    slug: "burn-heal",
    name: "Burn Heal",
    description: "See .mart page 5 for details.",
    emoji: "🔥",
    category: "cure",
    page: 5,
    price: 250,
    index: 45,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/burn-heal.png",
  },
  {
    id: "iceheal",
    slug: "ice-heal",
    name: "Ice Heal",
    description: "See .mart page 5 for details.",
    emoji: "🧊",
    category: "cure",
    page: 5,
    price: 250,
    index: 46,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ice-heal.png",
  },
  {
    id: "fullheal",
    slug: "full-heal",
    name: "Full Heal",
    description: "See .mart page 5 for details.",
    emoji: "💚",
    category: "cure",
    page: 5,
    price: 600,
    index: 47,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/full-heal.png",
  },
  {
    id: "berryjuice",
    slug: "berry-juice",
    name: "Berry Juice",
    description: "See .mart page 5 for details.",
    emoji: "🍒",
    category: "cure",
    page: 5,
    price: 100,
    index: 48,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/berry-juice.png",
  },
  {
    id: "ragecandybar",
    slug: "rage-candy-bar",
    name: "Rage Candy Bar",
    description: "See .mart page 5 for details.",
    emoji: "🍫",
    category: "cure",
    page: 5,
    price: 350,
    index: 49,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rage-candy-bar.png",
  },
  {
    id: "hpup",
    slug: "hp-up",
    name: "Hp Up",
    description: "See .mart page 6 for details.",
    emoji: "❤️",
    category: "vitamin",
    page: 6,
    price: 5000,
    index: 50,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hp-up.png",
  },
  {
    id: "protein",
    slug: "protein",
    name: "Protein",
    description: "See .mart page 6 for details.",
    emoji: "💪",
    category: "vitamin",
    page: 6,
    price: 5000,
    index: 51,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/protein.png",
  },
  {
    id: "iron",
    slug: "iron",
    name: "Iron",
    description: "See .mart page 6 for details.",
    emoji: "🛡️",
    category: "vitamin",
    page: 6,
    price: 5000,
    index: 52,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/iron.png",
  },
  {
    id: "calcium",
    slug: "calcium",
    name: "Calcium",
    description: "See .mart page 6 for details.",
    emoji: "🔮",
    category: "vitamin",
    page: 6,
    price: 5000,
    index: 53,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/calcium.png",
  },
  {
    id: "zinc",
    slug: "zinc",
    name: "Zinc",
    description: "See .mart page 6 for details.",
    emoji: "🔵",
    category: "vitamin",
    page: 6,
    price: 5000,
    index: 54,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/zinc.png",
  },
  {
    id: "carbos",
    slug: "carbos",
    name: "Carbos",
    description: "See .mart page 6 for details.",
    emoji: "💨",
    category: "vitamin",
    page: 6,
    price: 5000,
    index: 55,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/carbos.png",
  },
  {
    id: "ppup",
    slug: "pp-up",
    name: "Pp Up",
    description: "See .mart page 6 for details.",
    emoji: "🔋",
    category: "vitamin",
    page: 6,
    price: 3000,
    index: 56,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pp-up.png",
  },
  {
    id: "ppmax",
    slug: "pp-max",
    name: "Pp Max",
    description: "See .mart page 6 for details.",
    emoji: "⚡",
    category: "vitamin",
    page: 6,
    price: 9800,
    index: 57,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pp-max.png",
  },
  {
    id: "keystone",
    slug: "key-stone",
    name: "Key Stone",
    description: "See .mart page 7 for details.",
    emoji: "💎",
    category: "key",
    page: 7,
    price: 15000,
    index: 58,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/key-stone.png",
  },
  {
    id: "luckyegg",
    slug: "lucky-egg",
    name: "Lucky Egg",
    description: "See .mart page 7 for details.",
    emoji: "🥚",
    category: "key",
    page: 7,
    price: 2500,
    index: 59,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lucky-egg.png",
  },
  {
    id: "amuletcoin",
    slug: "amulet-coin",
    name: "Amulet Coin",
    description: "See .mart page 7 for details.",
    emoji: "🪙",
    category: "key",
    page: 7,
    price: 3000,
    index: 60,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/amulet-coin.png",
  },
  {
    id: "smokeball",
    slug: "smoke-ball",
    name: "Smoke Ball",
    description: "See .mart page 7 for details.",
    emoji: "💨",
    category: "key",
    page: 7,
    price: 1200,
    index: 61,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/smoke-ball.png",
  },
  {
    id: "escaperope",
    slug: "escape-rope",
    name: "Escape Rope",
    description: "See .mart page 7 for details.",
    emoji: "🪢",
    category: "key",
    page: 7,
    price: 550,
    index: 62,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/escape-rope.png",
  },
  {
    id: "rarecandy",
    slug: "rare-candy",
    name: "Rare Candy",
    description: "See .mart page 7 for details.",
    emoji: "🍬",
    category: "key",
    page: 7,
    price: 4800,
    index: 63,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rare-candy.png",
  },
  {
    id: "abomasite",
    slug: "abomasite",
    name: "Abomasite",
    description: "Mega Evolves Abomasnow → Mega Abomasnow. Requires an equipped Key Stone.",
    emoji: "❄️",
    category: "mega",
    page: 8,
    price: 25000,
    index: 64,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/abomasite.png",
  },
  {
    id: "absolite",
    slug: "absolite",
    name: "Absolite",
    description: "Mega Evolves Absol → Mega Absol. Requires an equipped Key Stone.",
    emoji: "🌑",
    category: "mega",
    page: 8,
    price: 25000,
    index: 65,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/absolite.png",
  },
  {
    id: "aerodactylite",
    slug: "aerodactylite",
    name: "Aerodactylite",
    description: "Mega Evolves Aerodactyl → Mega Aerodactyl. Requires an equipped Key Stone.",
    emoji: "🦖",
    category: "mega",
    page: 8,
    price: 25000,
    index: 66,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/aerodactylite.png",
  },
  {
    id: "aggronite",
    slug: "aggronite",
    name: "Aggronite",
    description: "Mega Evolves Aggron → Mega Aggron. Requires an equipped Key Stone.",
    emoji: "⚙️",
    category: "mega",
    page: 8,
    price: 25000,
    index: 67,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/aggronite.png",
  },
  {
    id: "alakazite",
    slug: "alakazite",
    name: "Alakazite",
    description: "Mega Evolves Alakazam → Mega Alakazam. Requires an equipped Key Stone.",
    emoji: "🥄",
    category: "mega",
    page: 8,
    price: 25000,
    index: 68,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/alakazite.png",
  },
  {
    id: "altarianite",
    slug: "altarianite",
    name: "Altarianite",
    description: "Mega Evolves Altaria → Mega Altaria. Requires an equipped Key Stone.",
    emoji: "☁️",
    category: "mega",
    page: 8,
    price: 25000,
    index: 69,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/altarianite.png",
  },
  {
    id: "ampharosite",
    slug: "ampharosite",
    name: "Ampharosite",
    description: "Mega Evolves Ampharos → Mega Ampharos. Requires an equipped Key Stone.",
    emoji: "⚡",
    category: "mega",
    page: 8,
    price: 25000,
    index: 70,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ampharosite.png",
  },
  {
    id: "audinite",
    slug: "audinite",
    name: "Audinite",
    description: "Mega Evolves Audino → Mega Audino. Requires an equipped Key Stone.",
    emoji: "💗",
    category: "mega",
    page: 8,
    price: 25000,
    index: 71,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/audinite.png",
  },
  {
    id: "banettite",
    slug: "banettite",
    name: "Banettite",
    description: "Mega Evolves Banette → Mega Banette. Requires an equipped Key Stone.",
    emoji: "👻",
    category: "mega",
    page: 8,
    price: 25000,
    index: 72,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/banettite.png",
  },
  {
    id: "beedrillite",
    slug: "beedrillite",
    name: "Beedrillite",
    description: "Mega Evolves Beedrill → Mega Beedrill. Requires an equipped Key Stone.",
    emoji: "🐝",
    category: "mega",
    page: 8,
    price: 25000,
    index: 73,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/beedrillite.png",
  },
  {
    id: "blastoisinite",
    slug: "blastoisinite",
    name: "Blastoisinite",
    description: "Mega Evolves Blastoise → Mega Blastoise. Requires an equipped Key Stone.",
    emoji: "💧",
    category: "mega",
    page: 8,
    price: 25000,
    index: 74,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/blastoisinite.png",
  },
  {
    id: "blazikenite",
    slug: "blazikenite",
    name: "Blazikenite",
    description: "Mega Evolves Blaziken → Mega Blaziken. Requires an equipped Key Stone.",
    emoji: "🔥",
    category: "mega",
    page: 8,
    price: 25000,
    index: 75,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/blazikenite.png",
  },
  {
    id: "cameruptite",
    slug: "cameruptite",
    name: "Cameruptite",
    description: "Mega Evolves Camerupt → Mega Camerupt. Requires an equipped Key Stone.",
    emoji: "🌋",
    category: "mega",
    page: 8,
    price: 25000,
    index: 76,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/cameruptite.png",
  },
  {
    id: "charizarditex",
    slug: "charizardite-x",
    name: "Charizardite X",
    description: "Mega Evolves Charizard → Mega Charizard X. Requires an equipped Key Stone.",
    emoji: "🐉",
    category: "mega",
    page: 8,
    price: 35000,
    index: 77,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/charizardite-x.png",
  },
  {
    id: "charizarditey",
    slug: "charizardite-y",
    name: "Charizardite Y",
    description: "Mega Evolves Charizard → Mega Charizard Y. Requires an equipped Key Stone.",
    emoji: "☀️",
    category: "mega",
    page: 8,
    price: 35000,
    index: 78,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/charizardite-y.png",
  },
  {
    id: "diancite",
    slug: "diancite",
    name: "Diancite",
    description: "Mega Evolves Diancie → Mega Diancie. Requires an equipped Key Stone.",
    emoji: "💎",
    category: "mega",
    page: 8,
    price: 25000,
    index: 79,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/diancite.png",
  },
  {
    id: "galladite",
    slug: "galladite",
    name: "Galladite",
    description: "Mega Evolves Gallade → Mega Gallade. Requires an equipped Key Stone.",
    emoji: "🗡️",
    category: "mega",
    page: 8,
    price: 25000,
    index: 80,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/galladite.png",
  },
  {
    id: "garchompite",
    slug: "garchompite",
    name: "Garchompite",
    description: "Mega Evolves Garchomp → Mega Garchomp. Requires an equipped Key Stone.",
    emoji: "🦈",
    category: "mega",
    page: 8,
    price: 25000,
    index: 81,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/garchompite.png",
  },
  {
    id: "gardevoirite",
    slug: "gardevoirite",
    name: "Gardevoirite",
    description: "Mega Evolves Gardevoir → Mega Gardevoir. Requires an equipped Key Stone.",
    emoji: "🌸",
    category: "mega",
    page: 8,
    price: 25000,
    index: 82,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/gardevoirite.png",
  },
  {
    id: "gengarite",
    slug: "gengarite",
    name: "Gengarite",
    description: "Mega Evolves Gengar → Mega Gengar. Requires an equipped Key Stone.",
    emoji: "👻",
    category: "mega",
    page: 8,
    price: 25000,
    index: 83,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/gengarite.png",
  },
  {
    id: "glalitite",
    slug: "glalitite",
    name: "Glalitite",
    description: "Mega Evolves Glalie → Mega Glalie. Requires an equipped Key Stone.",
    emoji: "🧊",
    category: "mega",
    page: 8,
    price: 25000,
    index: 84,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/glalitite.png",
  },
  {
    id: "gyaradosite",
    slug: "gyaradosite",
    name: "Gyaradosite",
    description: "Mega Evolves Gyarados → Mega Gyarados. Requires an equipped Key Stone.",
    emoji: "🌊",
    category: "mega",
    page: 8,
    price: 25000,
    index: 85,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/gyaradosite.png",
  },
  {
    id: "heracronite",
    slug: "heracronite",
    name: "Heracronite",
    description: "Mega Evolves Heracross → Mega Heracross. Requires an equipped Key Stone.",
    emoji: "🪲",
    category: "mega",
    page: 8,
    price: 25000,
    index: 86,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heracronite.png",
  },
  {
    id: "houndoominite",
    slug: "houndoominite",
    name: "Houndoominite",
    description: "Mega Evolves Houndoom → Mega Houndoom. Requires an equipped Key Stone.",
    emoji: "🐺",
    category: "mega",
    page: 8,
    price: 25000,
    index: 87,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/houndoominite.png",
  },
  {
    id: "kangaskhanite",
    slug: "kangaskhanite",
    name: "Kangaskhanite",
    description: "Mega Evolves Kangaskhan → Mega Kangaskhan. Requires an equipped Key Stone.",
    emoji: "🦘",
    category: "mega",
    page: 8,
    price: 25000,
    index: 88,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kangaskhanite.png",
  },
  {
    id: "latiasite",
    slug: "latiasite",
    name: "Latiasite",
    description: "Mega Evolves Latias → Mega Latias. Requires an equipped Key Stone.",
    emoji: "🪽",
    category: "mega",
    page: 8,
    price: 25000,
    index: 89,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/latiasite.png",
  },
  {
    id: "latiosite",
    slug: "latiosite",
    name: "Latiosite",
    description: "Mega Evolves Latios → Mega Latios. Requires an equipped Key Stone.",
    emoji: "🪽",
    category: "mega",
    page: 8,
    price: 25000,
    index: 90,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/latiosite.png",
  },
  {
    id: "lopunnite",
    slug: "lopunnite",
    name: "Lopunnite",
    description: "Mega Evolves Lopunny → Mega Lopunny. Requires an equipped Key Stone.",
    emoji: "🐰",
    category: "mega",
    page: 8,
    price: 25000,
    index: 91,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lopunnite.png",
  },
  {
    id: "lucarionite",
    slug: "lucarionite",
    name: "Lucarionite",
    description: "Mega Evolves Lucario → Mega Lucario. Requires an equipped Key Stone.",
    emoji: "🥊",
    category: "mega",
    page: 8,
    price: 25000,
    index: 92,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lucarionite.png",
  },
  {
    id: "manectite",
    slug: "manectite",
    name: "Manectite",
    description: "Mega Evolves Manectric → Mega Manectric. Requires an equipped Key Stone.",
    emoji: "⚡",
    category: "mega",
    page: 8,
    price: 25000,
    index: 93,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/manectite.png",
  },
  {
    id: "mawilite",
    slug: "mawilite",
    name: "Mawilite",
    description: "Mega Evolves Mawile → Mega Mawile. Requires an equipped Key Stone.",
    emoji: "🦷",
    category: "mega",
    page: 8,
    price: 25000,
    index: 94,
    imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mawilite.png",
  },
  {
    id: "medichamite",
    slug: "medichamite",
    name: "Medichamite",
    description: "Mega Evolves Medicham → Mega Medicham. Requires an equipped Key Stone.",
    emoji: "🧘",
    category: "mega",
    page: 8,
    price: 25000,
    index: 95,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/medichamite.png",
  },
  {
    id: "metagrossite",
    slug: "metagrossite",
    name: "Metagrossite",
    description: "Mega Evolves Metagross → Mega Metagross. Requires an equipped Key Stone.",
    emoji: "🤖",
    category: "mega",
    page: 8,
    price: 25000,
    index: 96,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/metagrossite.png",
  },
  {
    id: "mewtwonitex",
    slug: "mewtwonite-x",
    name: "Mewtwonite X",
    description: "Mega Evolves Mewtwo → Mega Mewtwo X. Requires an equipped Key Stone.",
    emoji: "🧬",
    category: "mega",
    page: 8,
    price: 35000,
    index: 97,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mewtwonite-x.png",
  },
  {
    id: "mewtwonitey",
    slug: "mewtwonite-y",
    name: "Mewtwonite Y",
    description: "Mega Evolves Mewtwo → Mega Mewtwo Y. Requires an equipped Key Stone.",
    emoji: "🧬",
    category: "mega",
    page: 8,
    price: 35000,
    index: 98,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mewtwonite-y.png",
  },
  {
    id: "pidgeotite",
    slug: "pidgeotite",
    name: "Pidgeotite",
    description: "Mega Evolves Pidgeot → Mega Pidgeot. Requires an equipped Key Stone.",
    emoji: "🦅",
    category: "mega",
    page: 8,
    price: 25000,
    index: 99,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pidgeotite.png",
  },
  {
    id: "pinsirite",
    slug: "pinsirite",
    name: "Pinsirite",
    description: "Mega Evolves Pinsir → Mega Pinsir. Requires an equipped Key Stone.",
    emoji: "🪲",
    category: "mega",
    page: 8,
    price: 25000,
    index: 100,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pinsirite.png",
  },
  {
    id: "sablenite",
    slug: "sablenite",
    name: "Sablenite",
    description: "Mega Evolves Sableye → Mega Sableye. Requires an equipped Key Stone.",
    emoji: "💎",
    category: "mega",
    page: 8,
    price: 25000,
    index: 101,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sablenite.png",
  },
  {
    id: "salamencite",
    slug: "salamencite",
    name: "Salamencite",
    description: "Mega Evolves Salamence → Mega Salamence. Requires an equipped Key Stone.",
    emoji: "🐲",
    category: "mega",
    page: 8,
    price: 25000,
    index: 102,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/salamencite.png",
  },
  {
    id: "sceptilite",
    slug: "sceptilite",
    name: "Sceptilite",
    description: "Mega Evolves Sceptile → Mega Sceptile. Requires an equipped Key Stone.",
    emoji: "🌿",
    category: "mega",
    page: 8,
    price: 25000,
    index: 103,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sceptilite.png",
  },
  {
    id: "scizorite",
    slug: "scizorite",
    name: "Scizorite",
    description: "Mega Evolves Scizor → Mega Scizor. Requires an equipped Key Stone.",
    emoji: "✂️",
    category: "mega",
    page: 8,
    price: 25000,
    index: 104,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/scizorite.png",
  },
  {
    id: "sharpedonite",
    slug: "sharpedonite",
    name: "Sharpedonite",
    description: "Mega Evolves Sharpedo → Mega Sharpedo. Requires an equipped Key Stone.",
    emoji: "🦈",
    category: "mega",
    page: 8,
    price: 25000,
    index: 105,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sharpedonite.png",
  },
  {
    id: "slowbronite",
    slug: "slowbronite",
    name: "Slowbronite",
    description: "Mega Evolves Slowbro → Mega Slowbro. Requires an equipped Key Stone.",
    emoji: "🐚",
    category: "mega",
    page: 8,
    price: 25000,
    index: 106,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/slowbronite.png",
  },
  {
    id: "steelixite",
    slug: "steelixite",
    name: "Steelixite",
    description: "Mega Evolves Steelix → Mega Steelix. Requires an equipped Key Stone.",
    emoji: "🐍",
    category: "mega",
    page: 8,
    price: 25000,
    index: 107,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/steelixite.png",
  },
  {
    id: "swampertite",
    slug: "swampertite",
    name: "Swampertite",
    description: "Mega Evolves Swampert → Mega Swampert. Requires an equipped Key Stone.",
    emoji: "💧",
    category: "mega",
    page: 8,
    price: 25000,
    index: 108,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/swampertite.png",
  },
  {
    id: "tyranitarite",
    slug: "tyranitarite",
    name: "Tyranitarite",
    description: "Mega Evolves Tyranitar → Mega Tyranitar. Requires an equipped Key Stone.",
    emoji: "🦖",
    category: "mega",
    page: 8,
    price: 25000,
    index: 109,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tyranitarite.png",
  },
  {
    id: "venusaurite",
    slug: "venusaurite",
    name: "Venusaurite",
    description: "Mega Evolves Venusaur → Mega Venusaur. Requires an equipped Key Stone.",
    emoji: "🌺",
    category: "mega",
    page: 8,
    price: 25000,
    index: 110,
    imageUrl:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/venusaurite.png",
  },
] as const;
