import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState, type CSSProperties } from "react";
import { Coins, Crown, Layers3, PackageOpen, Trophy } from "lucide-react";
import { AppShell } from "@/components/aidoru/AppShell";
import { UserAvatar } from "@/components/aidoru/UserAvatar";
import { useSession } from "@/components/aidoru/session";
import { fetchCardsLeaderboard, fetchCoinsLeaderboard, fetchGymsLeaderboard, fetchPokemonLeaderboard, fetchXpLeaderboard } from "@/lib/aidoru.functions";
import { formatCompactCoins, type LeaderboardMetric, type LeaderboardRow } from "@/lib/game";

export const Route = createFileRoute("/dashboard")({ head: () => ({ meta: [{ title: "Leaderboards — AIDORU" }, { name: "description", content: "Live AIDORU rankings with real bot usernames, avatars, and trainer statistics." }] }), component: LeaderboardPage });
const METRICS: { id: LeaderboardMetric; label: string; icon: typeof Layers3 }[] = [{ id: "xp", label: "XP", icon: Layers3 }, { id: "coins", label: "Ryu", icon: Coins }, { id: "cards", label: "Cards", icon: PackageOpen }, { id: "pokemon", label: "Pokémon", icon: Crown }, { id: "gyms", label: "Gym Achievements", icon: Trophy }];
const LEADERBOARD_SNAPSHOT_PREFIX = "aidoru:leaderboard:snapshot:";
type LeaderboardSnapshot = { rows: LeaderboardRow[]; savedAt: number };
function readLeaderboardSnapshot(metric: LeaderboardMetric): LeaderboardSnapshot | undefined { if (typeof window === "undefined") return undefined; try { const parsed: unknown = JSON.parse(window.sessionStorage.getItem(`${LEADERBOARD_SNAPSHOT_PREFIX}${metric}`) ?? "null"); if (Array.isArray(parsed)) return { rows: parsed as LeaderboardRow[], savedAt: 0 }; if (parsed && typeof parsed === "object" && Array.isArray((parsed as { rows?: unknown }).rows)) return { rows: (parsed as { rows: LeaderboardRow[] }).rows, savedAt: Number((parsed as { savedAt?: unknown }).savedAt) || 0 }; } catch {} return undefined; }
function writeLeaderboardSnapshot(metric: LeaderboardMetric, rows: LeaderboardRow[]) { try { window.sessionStorage.setItem(`${LEADERBOARD_SNAPSHOT_PREFIX}${metric}`, JSON.stringify({ rows, savedAt: Date.now() })); } catch {} }
function LeaderboardPage() { return <AppShell title="Leaderboards" subtitle="Every ranking is pulled from the live trainer community."><LeaderboardBody /></AppShell>; }
function LeaderboardBody() {
  const { data: user } = useSession(); const [metric, setMetric] = useState<LeaderboardMetric>("xp");
  const fetchXP = useServerFn(fetchXpLeaderboard); const fetchCoins = useServerFn(fetchCoinsLeaderboard); const fetchCards = useServerFn(fetchCardsLeaderboard); const fetchPokemon = useServerFn(fetchPokemonLeaderboard); const fetchGyms = useServerFn(fetchGymsLeaderboard);
  const leaderboardFn = metric === "xp" ? fetchXP : metric === "coins" ? fetchCoins : metric === "cards" ? fetchCards : metric === "pokemon" ? fetchPokemon : fetchGyms; const snapshot = readLeaderboardSnapshot(metric);
  const boardQuery = useQuery({ queryKey: ["aidoru", "leaderboard", metric], queryFn: async () => { const result = await Promise.race([leaderboardFn(), new Promise<never>((_, reject) => window.setTimeout(() => reject(new Error("Leaderboard timed out after 12 seconds.")), 12_000))]); writeLeaderboardSnapshot(metric, result); return result; }, initialData: snapshot?.rows, initialDataUpdatedAt: snapshot?.savedAt || 0, staleTime: 120_000, gcTime: 10 * 60_000, retry: false, placeholderData: (previous) => previous, refetchOnMount: true });
  if (!user) return null; const board = [...(boardQuery.data ?? [])].sort((a, b) => Number(b.score) - Number(a.score) || a.name.localeCompare(b.name)); const podium = board.slice(0, 3);
  return <div className="space-y-6 pb-10"><section className="leaderboard-shell"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="hof-kicker">Live community rankings</p><h2 className="hof-heading mt-1 text-4xl tracking-tight sm:text-6xl">Global Peeps</h2></div><div className="leaderboard-live-pill">{boardQuery.isFetching ? "SYNCING" : metric.toUpperCase()} · LIVE</div></div><div className="leaderboard-tabs mt-6" role="tablist">{METRICS.map(({ id, label, icon: Icon }) => <button key={id} type="button" data-active={metric === id} onClick={() => setMetric(id)} className="leaderboard-tab"><Icon className="size-5" /><span>{label}</span></button>)}</div>{boardQuery.isLoading && <div className="py-12 text-center text-sm text-muted-foreground">Loading rankings…</div>}{boardQuery.isError && <div className="py-12 text-center text-sm text-rose-200">Rankings are taking too long to respond. Showing the last saved snapshot when available.</div>}{!boardQuery.isLoading && !boardQuery.isError && board.length === 0 && <div className="py-12 text-center text-sm text-muted-foreground">No ranked trainers yet.</div>}{board.length > 0 && <><div className="leaderboard-podium mt-8">{[podium[1], podium[0], podium[2]].map((row, index) => row && <LeaderboardCard key={row.id} row={row} rank={row === podium[0] ? 1 : index === 0 ? 2 : 3} podium />)}</div><div className="mt-5 space-y-3">{board.slice(3).map((row, index) => <LeaderboardCard key={`${row.id}-${index}`} row={row} rank={index + 4} />)}</div></>}</section></div>;
}
function trainerCollectionLabel(row: LeaderboardRow) {
  const pokemon = row.pokemonCount || (row.scoreLabel === "POKÉMON" ? row.score : 0);
  const cards = row.cardCount || (row.scoreLabel === "CARDS" ? row.score : 0);
  return `${pokemon} Pokémon · ${cards} cards`;
}
function LeaderboardCard({ row, rank, podium = false }: { row: LeaderboardRow; rank: number; podium?: boolean }) { return <div className={podium ? "leaderboard-podium-card" : "leaderboard-rank-row"} style={row.profileBackground ? leaderboardBackgroundStyle(row.profileBackground) : undefined}><span className={podium ? "leaderboard-place" : "leaderboard-rank"}>{podium ? rank : `#${rank}`}</span><UserAvatar name={row.name} src={row.avatarUrl} videoSrc={row.avatarVideoUrl} frame={row.profileFrame} className={podium ? "leaderboard-podium-avatar" : "leaderboard-rank-avatar"} /><div className="min-w-0 flex-1"><p className={podium ? "leaderboard-podium-name" : "leaderboard-rank-name"}>{row.name}</p>{!podium && <p className="leaderboard-rank-meta">{row.title} · LV {row.trainerLevel} · {trainerCollectionLabel(row)}</p>}</div><p className={podium ? "leaderboard-score" : "leaderboard-rank-score"}>{formatCompactCoins(row.score)} <span>{row.scoreLabel}</span></p></div>; }
function leaderboardBackgroundStyle(background: string): CSSProperties { return { backgroundImage: `linear-gradient(90deg, rgba(8, 12, 20, 0.88), rgba(8, 12, 20, 0.55)), url("${background}")` }; }
