/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HalloweenRouteImport } from './routes/Halloween'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GuildRouteImport } from './routes/guild'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MartRouteImport } from './routes/mart'
import { Route as ModApplicationRouteImport } from './routes/mod-application'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuctionMediaAssetIdRouteImport } from './routes/auction-media.$assetId'
import { Route as BattleRoomIdRouteImport } from './routes/battle.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HalloweenRoute = HalloweenRouteImport.update({
  id: '/Halloween',
  path: '/Halloween',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildRoute = GuildRouteImport.update({
  id: '/guild',
  path: '/guild',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MartRoute = MartRouteImport.update({
  id: '/mart',
  path: '/mart',
  getParentRoute: () => rootRouteImport,
} as any)
const ModApplicationRoute = ModApplicationRouteImport.update({
  id: '/mod-application',
  path: '/mod-application',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionMediaAssetIdRoute = AuctionMediaAssetIdRouteImport.update({
  id: '/auction-media/$assetId',
  path: '/auction-media/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoomIdRoute = BattleRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => BattleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Halloween': typeof HalloweenRoute
  '/auctions': typeof AuctionsRoute
  '/battle': typeof BattleRouteWithChildren
  '/cards': typeof CardsRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/guild': typeof GuildRoute
  '/journey': typeof JourneyRoute
  '/mart': typeof MartRoute
  '/mod-application': typeof ModApplicationRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/auction-media/$assetId': typeof AuctionMediaAssetIdRoute
  '/battle/$roomId': typeof BattleRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Halloween': typeof HalloweenRoute
  '/auctions': typeof AuctionsRoute
  '/battle': typeof BattleRouteWithChildren
  '/cards': typeof CardsRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/guild': typeof GuildRoute
  '/journey': typeof JourneyRoute
  '/mart': typeof MartRoute
  '/mod-application': typeof ModApplicationRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/auction-media/$assetId': typeof AuctionMediaAssetIdRoute
  '/battle/$roomId': typeof BattleRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Halloween': typeof HalloweenRoute
  '/auctions': typeof AuctionsRoute
  '/battle': typeof BattleRouteWithChildren
  '/cards': typeof CardsRoute
  '/daily': typeof DailyRoute
  '/dashboard': typeof DashboardRoute
  '/guild': typeof GuildRoute
  '/journey': typeof JourneyRoute
  '/mart': typeof MartRoute
  '/mod-application': typeof ModApplicationRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/auction-media/$assetId': typeof AuctionMediaAssetIdRoute
  '/battle/$roomId': typeof BattleRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Halloween'
    | '/auctions'
    | '/battle'
    | '/cards'
    | '/daily'
    | '/dashboard'
    | '/guild'
    | '/journey'
    | '/mart'
    | '/mod-application'
    | '/pets'
    | '/profile'
    | '/auction-media/$assetId'
    | '/battle/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Halloween'
    | '/auctions'
    | '/battle'
    | '/cards'
    | '/daily'
    | '/dashboard'
    | '/guild'
    | '/journey'
    | '/mart'
    | '/mod-application'
    | '/pets'
    | '/profile'
    | '/auction-media/$assetId'
    | '/battle/$roomId'
  id:
    | '__root__'
    | '/'
    | '/Halloween'
    | '/auctions'
    | '/battle'
    | '/cards'
    | '/daily'
    | '/dashboard'
    | '/guild'
    | '/journey'
    | '/mart'
    | '/mod-application'
    | '/pets'
    | '/profile'
    | '/auction-media/$assetId'
    | '/battle/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HalloweenRoute: typeof HalloweenRoute
  AuctionsRoute: typeof AuctionsRoute
  BattleRoute: typeof BattleRouteWithChildren
  CardsRoute: typeof CardsRoute
  DailyRoute: typeof DailyRoute
  DashboardRoute: typeof DashboardRoute
  GuildRoute: typeof GuildRoute
  JourneyRoute: typeof JourneyRoute
  MartRoute: typeof MartRoute
  ModApplicationRoute: typeof ModApplicationRoute
  PetsRoute: typeof PetsRoute
  ProfileRoute: typeof ProfileRoute
  AuctionMediaAssetIdRoute: typeof AuctionMediaAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Halloween': {
      id: '/Halloween'
      path: '/Halloween'
      fullPath: '/Halloween'
      preLoaderRoute: typeof HalloweenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild': {
      id: '/guild'
      path: '/guild'
      fullPath: '/guild'
      preLoaderRoute: typeof GuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mart': {
      id: '/mart'
      path: '/mart'
      fullPath: '/mart'
      preLoaderRoute: typeof MartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-application': {
      id: '/mod-application'
      path: '/mod-application'
      fullPath: '/mod-application'
      preLoaderRoute: typeof ModApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction-media/$assetId': {
      id: '/auction-media/$assetId'
      path: '/auction-media/$assetId'
      fullPath: '/auction-media/$assetId'
      preLoaderRoute: typeof AuctionMediaAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$roomId': {
      id: '/battle/$roomId'
      path: '/$roomId'
      fullPath: '/battle/$roomId'
      preLoaderRoute: typeof BattleRoomIdRouteImport
      parentRoute: typeof BattleRoute
    }
  }
}

interface BattleRouteChildren {
  BattleRoomIdRoute: typeof BattleRoomIdRoute
}

const BattleRouteChildren: BattleRouteChildren = {
  BattleRoomIdRoute: BattleRoomIdRoute,
}

const BattleRouteWithChildren =
  BattleRoute._addFileChildren(BattleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HalloweenRoute: HalloweenRoute,
  AuctionsRoute: AuctionsRoute,
  BattleRoute: BattleRouteWithChildren,
  CardsRoute: CardsRoute,
  DailyRoute: DailyRoute,
  DashboardRoute: DashboardRoute,
  GuildRoute: GuildRoute,
  JourneyRoute: JourneyRoute,
  MartRoute: MartRoute,
  ModApplicationRoute: ModApplicationRoute,
  PetsRoute: PetsRoute,
  ProfileRoute: ProfileRoute,
  AuctionMediaAssetIdRoute: AuctionMediaAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
